# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 503a9c6c372451505b213a3f081afdcc812683bc1760ab188a94d69bdd2b8b4d076f9278f1a00aaf50de68f2e29cf4fa08f64817f504ff884166e8ee77738a2c

test:
  secret_key_base: 623a62bd552c16eafb2da3b9c87236cb5703f29da0eee8b9d82a0c0ac7f8d473ea45087a11690923cace0c179db78ecad044806a4e7715e4e1d7b6e952b3ad2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
